package website.skylorbeck.sentimentality3.sentimentality3;

import com.google.gson.JsonObject;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.fabricmc.tinyremapper.extension.mixin.common.Logger;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.HayBlock;
import net.minecraft.entity.EquipmentSlot;
import net.minecraft.item.*;
import net.minecraft.particle.DefaultParticleType;
import net.minecraft.util.Identifier;
import website.skylorbeck.minecraft.skylorlib.furnaces.ExtraBlastFurnaceBlock;
import website.skylorbeck.minecraft.skylorlib.furnaces.ExtraFurnaceBlock;
import website.skylorbeck.minecraft.skylorlib.furnaces.ExtraSmokerBlock;
import website.skylorbeck.minecraft.skylorlib.misc.CompressedBlock;
import website.skylorbeck.minecraft.skylorlib.tools.ExtraAxeItem;
import website.skylorbeck.minecraft.skylorlib.tools.ExtraHoeItem;
import website.skylorbeck.minecraft.skylorlib.tools.ExtraPickaxeItem;
import website.skylorbeck.minecraft.skylorlib.tools.ExtraToolMaterials;

public class Declarer {
    public static final Logger logger = new Logger(Logger.Level.ERROR);

    public static final ItemGroup sentimentality3 = FabricItemGroupBuilder.build(
            new Identifier("sentimentality3", "category"),
            () -> new ItemStack(Declarer.chunk_loader));
    //entities
    public static DefaultParticleType END_FIRE_FLAME;

    //gliders
    //custom personal items
    public static final Item chunk_loader = new Chunkloader(new FabricItemSettings().group(sentimentality3));
    public static final Item personal_daylight_detector = new PDDItem(new FabricItemSettings().group(sentimentality3));
    public static final Item slime_chunk_locator = new SlimeChunkLocator(new FabricItemSettings().group(sentimentality3));
    //misc items
    public static final Item fleather = new Item(new FabricItemSettings().group(sentimentality3));
    public static final Item small_stick_bundle = new Item(new FabricItemSettings().group(sentimentality3));
    public static final Item large_stick_bundle = new Item(new FabricItemSettings().group(sentimentality3));
    public static final Block feather_block_block = new HayBlock(FabricBlockSettings.copyOf(Blocks.HAY_BLOCK));
    public static final BlockItem feather_block = new BlockItem(feather_block_block, new FabricItemSettings().group(sentimentality3));
    public static final Block charcoal_block_block = new Block(FabricBlockSettings.copyOf(Blocks.COAL_BLOCK).requiresTool());
    public static final BlockItem charcoal_block = new BlockItem(charcoal_block_block, new FabricItemSettings().group(sentimentality3));
    public static final Item charcoal_nugget = new Item(new FabricItemSettings().group(sentimentality3));
    public static final Item coal_nugget = new Item(new FabricItemSettings().group(sentimentality3));
    //compressed cobble
    public static final Block monuple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 1);
    public static final BlockItem monuple_compressed_cobblestone = new BlockItem(monuple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 2);
    public static final BlockItem couple_compressed_cobblestone = new BlockItem(couple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 3);
    public static final BlockItem triple_compressed_cobblestone = new BlockItem(triple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_cobblestone = new BlockItem(quadruple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_cobblestone = new BlockItem(quintuple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_cobblestone = new BlockItem(sextuple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 7);
    public static final BlockItem septuple_compressed_cobblestone = new BlockItem(septuple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 8);
    public static final BlockItem octuple_compressed_cobblestone = new BlockItem(octuple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_cobblestone_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLESTONE).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_cobblestone = new BlockItem(nonuple_compressed_cobblestone_block, new FabricItemSettings().group(sentimentality3));
    //compressed dirt
    public static final Block monuple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 1);
    public static final BlockItem monuple_compressed_dirt = new BlockItem(monuple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 2);
    public static final BlockItem couple_compressed_dirt = new BlockItem(couple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 3);
    public static final BlockItem triple_compressed_dirt = new BlockItem(triple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_dirt = new BlockItem(quadruple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_dirt = new BlockItem(quintuple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_dirt = new BlockItem(sextuple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 7);
    public static final BlockItem septuple_compressed_dirt = new BlockItem(septuple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 8);
    public static final BlockItem octuple_compressed_dirt = new BlockItem(octuple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_dirt_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIRT).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_dirt = new BlockItem(nonuple_compressed_dirt_block, new FabricItemSettings().group(sentimentality3));
    //compressed granite
    public static final Block monuple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 1);
    public static final BlockItem monuple_compressed_granite = new BlockItem(monuple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 2);
    public static final BlockItem couple_compressed_granite = new BlockItem(couple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 3);
    public static final BlockItem triple_compressed_granite = new BlockItem(triple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_granite = new BlockItem(quadruple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_granite = new BlockItem(quintuple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_granite = new BlockItem(sextuple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 7);
    public static final BlockItem septuple_compressed_granite = new BlockItem(septuple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 8);
    public static final BlockItem octuple_compressed_granite = new BlockItem(octuple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_granite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRANITE).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_granite = new BlockItem(nonuple_compressed_granite_block, new FabricItemSettings().group(sentimentality3));
    //compressed diorite
    public static final Block monuple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 1);
    public static final BlockItem monuple_compressed_diorite = new BlockItem(monuple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 2);
    public static final BlockItem couple_compressed_diorite = new BlockItem(couple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 3);
    public static final BlockItem triple_compressed_diorite = new BlockItem(triple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_diorite = new BlockItem(quadruple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_diorite = new BlockItem(quintuple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_diorite = new BlockItem(sextuple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 7);
    public static final BlockItem septuple_compressed_diorite = new BlockItem(septuple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 8);
    public static final BlockItem octuple_compressed_diorite = new BlockItem(octuple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_diorite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.DIORITE).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_diorite = new BlockItem(nonuple_compressed_diorite_block, new FabricItemSettings().group(sentimentality3));
    //compressed andesite
    public static final Block monuple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 1);
    public static final BlockItem monuple_compressed_andesite = new BlockItem(monuple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 2);
    public static final BlockItem couple_compressed_andesite = new BlockItem(couple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 3);
    public static final BlockItem triple_compressed_andesite = new BlockItem(triple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_andesite = new BlockItem(quadruple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_andesite = new BlockItem(quintuple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_andesite = new BlockItem(sextuple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 7);
    public static final BlockItem septuple_compressed_andesite = new BlockItem(septuple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 8);
    public static final BlockItem octuple_compressed_andesite = new BlockItem(octuple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_andesite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.ANDESITE).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_andesite = new BlockItem(nonuple_compressed_andesite_block, new FabricItemSettings().group(sentimentality3));
    //compressed netherrack
    public static final Block monuple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 1);
    public static final BlockItem monuple_compressed_netherrack = new BlockItem(monuple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 2);
    public static final BlockItem couple_compressed_netherrack = new BlockItem(couple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 3);
    public static final BlockItem triple_compressed_netherrack = new BlockItem(triple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_netherrack = new BlockItem(quadruple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_netherrack = new BlockItem(quintuple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_netherrack = new BlockItem(sextuple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 7);
    public static final BlockItem septuple_compressed_netherrack = new BlockItem(septuple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 8);
    public static final BlockItem octuple_compressed_netherrack = new BlockItem(octuple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_netherrack_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.NETHERRACK).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_netherrack = new BlockItem(nonuple_compressed_netherrack_block, new FabricItemSettings().group(sentimentality3));
    //compressed sand
    public static final Block monuple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 1);
    public static final BlockItem monuple_compressed_sand = new BlockItem(monuple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 2);
    public static final BlockItem couple_compressed_sand = new BlockItem(couple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 3);
    public static final BlockItem triple_compressed_sand = new BlockItem(triple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_sand = new BlockItem(quadruple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_sand = new BlockItem(quintuple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_sand = new BlockItem(sextuple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 7);
    public static final BlockItem septuple_compressed_sand = new BlockItem(septuple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 8);
    public static final BlockItem octuple_compressed_sand = new BlockItem(octuple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_sand_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.SAND).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_sand = new BlockItem(nonuple_compressed_sand_block, new FabricItemSettings().group(sentimentality3));
    //compressed gravel
    public static final Block monuple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 1);
    public static final BlockItem monuple_compressed_gravel = new BlockItem(monuple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 2);
    public static final BlockItem couple_compressed_gravel = new BlockItem(couple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 3);
    public static final BlockItem triple_compressed_gravel = new BlockItem(triple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_gravel = new BlockItem(quadruple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_gravel = new BlockItem(quintuple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_gravel = new BlockItem(sextuple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 7);
    public static final BlockItem septuple_compressed_gravel = new BlockItem(septuple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 8);
    public static final BlockItem octuple_compressed_gravel = new BlockItem(octuple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_gravel_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.GRAVEL).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_gravel = new BlockItem(nonuple_compressed_gravel_block, new FabricItemSettings().group(sentimentality3));
    //compressed cobbled deepslate
    public static final Block monuple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 1);
    public static final BlockItem monuple_compressed_cobbled_deepslate = new BlockItem(monuple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 2);
    public static final BlockItem couple_compressed_cobbled_deepslate = new BlockItem(couple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 3);
    public static final BlockItem triple_compressed_cobbled_deepslate = new BlockItem(triple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_cobbled_deepslate = new BlockItem(quadruple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_cobbled_deepslate = new BlockItem(quintuple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_cobbled_deepslate = new BlockItem(sextuple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 7);
    public static final BlockItem septuple_compressed_cobbled_deepslate = new BlockItem(septuple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 8);
    public static final BlockItem octuple_compressed_cobbled_deepslate = new BlockItem(octuple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_cobbled_deepslate_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.COBBLED_DEEPSLATE).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_cobbled_deepslate = new BlockItem(nonuple_compressed_cobbled_deepslate_block, new FabricItemSettings().group(sentimentality3));

    //compressed tuff
    public static final Block monuple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 1);
    public static final BlockItem monuple_compressed_tuff = new BlockItem(monuple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 2);
    public static final BlockItem couple_compressed_tuff = new BlockItem(couple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 3);
    public static final BlockItem triple_compressed_tuff = new BlockItem(triple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_tuff = new BlockItem(quadruple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_tuff = new BlockItem(quintuple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_tuff = new BlockItem(sextuple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 7);
    public static final BlockItem septuple_compressed_tuff = new BlockItem(septuple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 8);
    public static final BlockItem octuple_compressed_tuff = new BlockItem(octuple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_tuff_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.TUFF).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_tuff = new BlockItem(nonuple_compressed_tuff_block, new FabricItemSettings().group(sentimentality3));
    //compressed calcite
    public static final Block monuple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 1);
    public static final BlockItem monuple_compressed_calcite = new BlockItem(monuple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block couple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 2);
    public static final BlockItem couple_compressed_calcite = new BlockItem(couple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block triple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 3);
    public static final BlockItem triple_compressed_calcite = new BlockItem(triple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quadruple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 4);
    public static final BlockItem quadruple_compressed_calcite = new BlockItem(quadruple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block quintuple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 5);
    public static final BlockItem quintuple_compressed_calcite = new BlockItem(quintuple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block sextuple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 6);
    public static final BlockItem sextuple_compressed_calcite = new BlockItem(sextuple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block septuple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 7);
    public static final BlockItem septuple_compressed_calcite = new BlockItem(septuple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block octuple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 8);
    public static final BlockItem octuple_compressed_calcite = new BlockItem(octuple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    public static final Block nonuple_compressed_calcite_block = new CompressedBlock(FabricBlockSettings.copyOf(Blocks.CALCITE).requiresTool(), 9);
    public static final BlockItem nonuple_compressed_calcite = new BlockItem(nonuple_compressed_calcite_block, new FabricItemSettings().group(sentimentality3));
    //furnaces
    public static final Block sandstone_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 0);
    public static final BlockItem sandstone_furnace = new BlockItem(sandstone_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block red_sandstone_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 0);
    public static final BlockItem red_sandstone_furnace = new BlockItem(red_sandstone_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block andesite_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 0);
    public static final BlockItem andesite_furnace = new BlockItem(andesite_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block granite_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 0);
    public static final BlockItem granite_furnace = new BlockItem(granite_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block diorite_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 0);
    public static final BlockItem diorite_furnace = new BlockItem(diorite_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block netherrack_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 1);
    public static final BlockItem netherrack_furnace = new BlockItem(netherrack_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block blackstone_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 1);
    public static final BlockItem blackstone_furnace = new BlockItem(blackstone_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block basalt_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 1);
    public static final BlockItem basalt_furnace = new BlockItem(basalt_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block endstone_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 2);
    public static final BlockItem endstone_furnace = new BlockItem(endstone_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block deepslate_furnaceblock = new ExtraFurnaceBlock(FabricBlockSettings.copyOf(Blocks.FURNACE).requiresTool(), 0);
    public static final BlockItem deepslate_furnace = new BlockItem(deepslate_furnaceblock, new FabricItemSettings().group(sentimentality3));
    //blast furnaces
    public static final Block sandstone_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem sandstone_blast_furnace = new BlockItem(sandstone_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block red_sandstone_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem red_sandstone_blast_furnace = new BlockItem(red_sandstone_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block andesite_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem andesite_blast_furnace = new BlockItem(andesite_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block granite_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem granite_blast_furnace = new BlockItem(granite_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block diorite_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem diorite_blast_furnace = new BlockItem(diorite_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block netherrack_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem netherrack_blast_furnace = new BlockItem(netherrack_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block blackstone_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem blackstone_blast_furnace = new BlockItem(blackstone_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block basalt_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem basalt_blast_furnace = new BlockItem(basalt_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block endstone_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem endstone_blast_furnace = new BlockItem(endstone_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    public static final Block deepslate_blast_furnaceblock = new ExtraBlastFurnaceBlock(FabricBlockSettings.copyOf(Blocks.BLAST_FURNACE).requiresTool());
    public static final BlockItem deepslate_blast_furnace = new BlockItem(deepslate_blast_furnaceblock, new FabricItemSettings().group(sentimentality3));
    //smokers
    public static final Block sandstone_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem sandstone_smoker = new BlockItem(sandstone_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block red_sandstone_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem red_sandstone_smoker = new BlockItem(red_sandstone_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block andesite_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem andesite_smoker = new BlockItem(andesite_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block granite_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem granite_smoker = new BlockItem(granite_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block diorite_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem diorite_smoker = new BlockItem(diorite_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block netherrack_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem netherrack_smoker = new BlockItem(netherrack_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block blackstone_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem blackstone_smoker = new BlockItem(blackstone_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block basalt_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem basalt_smoker = new BlockItem(basalt_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block endstone_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem endstone_smoker = new BlockItem(endstone_smokerblock, new FabricItemSettings().group(sentimentality3));
    public static final Block deepslate_smokerblock = new ExtraSmokerBlock(FabricBlockSettings.copyOf(Blocks.SMOKER).requiresTool());
    public static final BlockItem deepslate_smoker = new BlockItem(deepslate_smokerblock, new FabricItemSettings().group(sentimentality3));
    //wool armor
    public static final Item wool_helmet = new ExtraDyeableArmorItem(ExtraArmorMaterials.WOOL, EquipmentSlot.HEAD, new FabricItemSettings().group(sentimentality3));
    public static final Item wool_chestplate = new ExtraDyeableArmorItem(ExtraArmorMaterials.WOOL, EquipmentSlot.CHEST, new FabricItemSettings().group(sentimentality3));
    public static final Item wool_leggings = new ExtraDyeableArmorItem(ExtraArmorMaterials.WOOL, EquipmentSlot.LEGS, new FabricItemSettings().group(sentimentality3));
    public static final Item wool_boots = new ExtraDyeableArmorItem(ExtraArmorMaterials.WOOL, EquipmentSlot.FEET, new FabricItemSettings().group(sentimentality3));
    //copper armor
    public static final Item copper_helmet = new ArmorItem(ExtraArmorMaterials.COPPER, EquipmentSlot.HEAD, new FabricItemSettings().group(sentimentality3));
    public static final Item copper_chestplate = new ArmorItem(ExtraArmorMaterials.COPPER, EquipmentSlot.CHEST, new FabricItemSettings().group(sentimentality3));
    public static final Item copper_leggings = new ArmorItem(ExtraArmorMaterials.COPPER, EquipmentSlot.LEGS, new FabricItemSettings().group(sentimentality3));
    public static final Item copper_boots = new ArmorItem(ExtraArmorMaterials.COPPER, EquipmentSlot.FEET, new FabricItemSettings().group(sentimentality3));
    //tools
    public static final Item granite_sword = new SwordItem(ExtraToolMaterials.GRANITE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item granite_shovel = new ShovelItem(ExtraToolMaterials.GRANITE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item granite_pick = new ExtraPickaxeItem(ExtraToolMaterials.GRANITE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item granite_axe = new ExtraAxeItem(ExtraToolMaterials.GRANITE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item granite_hoe = new ExtraHoeItem(ExtraToolMaterials.GRANITE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item diorite_sword = new SwordItem(ExtraToolMaterials.DIORITE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item diorite_shovel = new ShovelItem(ExtraToolMaterials.DIORITE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item diorite_pick = new ExtraPickaxeItem(ExtraToolMaterials.DIORITE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item diorite_axe = new ExtraAxeItem(ExtraToolMaterials.DIORITE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item diorite_hoe = new ExtraHoeItem(ExtraToolMaterials.DIORITE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item andesite_sword = new SwordItem(ExtraToolMaterials.ANDESITE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item andesite_shovel = new ShovelItem(ExtraToolMaterials.ANDESITE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item andesite_pick = new ExtraPickaxeItem(ExtraToolMaterials.ANDESITE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item andesite_axe = new ExtraAxeItem(ExtraToolMaterials.ANDESITE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item andesite_hoe = new ExtraHoeItem(ExtraToolMaterials.ANDESITE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item quartz_sword = new SwordItem(ExtraToolMaterials.QUARTZ, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item quartz_shovel = new ShovelItem(ExtraToolMaterials.QUARTZ, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item quartz_pick = new ExtraPickaxeItem(ExtraToolMaterials.QUARTZ, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item quartz_axe = new ExtraAxeItem(ExtraToolMaterials.QUARTZ, 6.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item quartz_hoe = new ExtraHoeItem(ExtraToolMaterials.QUARTZ, -2, -1.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item netherrack_sword = new SwordItem(ExtraToolMaterials.NETHERRACK, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item netherrack_shovel = new ShovelItem(ExtraToolMaterials.NETHERRACK, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item netherrack_pick = new ExtraPickaxeItem(ExtraToolMaterials.NETHERRACK, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item netherrack_axe = new ExtraAxeItem(ExtraToolMaterials.NETHERRACK, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item netherrack_hoe = new ExtraHoeItem(ExtraToolMaterials.NETHERRACK, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item netherbrick_sword = new SwordItem(ExtraToolMaterials.NETHERBRICK, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item netherbrick_shovel = new ShovelItem(ExtraToolMaterials.NETHERBRICK, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item netherbrick_pick = new ExtraPickaxeItem(ExtraToolMaterials.NETHERBRICK, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item netherbrick_axe = new ExtraAxeItem(ExtraToolMaterials.NETHERBRICK, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item netherbrick_hoe = new ExtraHoeItem(ExtraToolMaterials.NETHERBRICK, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item rednetherbrick_sword = new SwordItem(ExtraToolMaterials.REDNETHERBRICK, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item rednetherbrick_shovel = new ShovelItem(ExtraToolMaterials.REDNETHERBRICK, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item rednetherbrick_pick = new ExtraPickaxeItem(ExtraToolMaterials.REDNETHERBRICK, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item rednetherbrick_axe = new ExtraAxeItem(ExtraToolMaterials.REDNETHERBRICK, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item rednetherbrick_hoe = new ExtraHoeItem(ExtraToolMaterials.REDNETHERBRICK, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item sandstone_sword = new SwordItem(ExtraToolMaterials.SANDSTONE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item sandstone_shovel = new ShovelItem(ExtraToolMaterials.SANDSTONE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item sandstone_pick = new ExtraPickaxeItem(ExtraToolMaterials.SANDSTONE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item sandstone_axe = new ExtraAxeItem(ExtraToolMaterials.SANDSTONE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item sandstone_hoe = new ExtraHoeItem(ExtraToolMaterials.SANDSTONE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item redsandstone_sword = new SwordItem(ExtraToolMaterials.REDSANDSTONE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item redsandstone_shovel = new ShovelItem(ExtraToolMaterials.REDSANDSTONE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item redsandstone_pick = new ExtraPickaxeItem(ExtraToolMaterials.REDSANDSTONE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item redsandstone_axe = new ExtraAxeItem(ExtraToolMaterials.REDSANDSTONE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item redsandstone_hoe = new ExtraHoeItem(ExtraToolMaterials.REDSANDSTONE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item redstone_sword = new SwordItem(ExtraToolMaterials.REDSTONE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item redstone_shovel = new ShovelItem(ExtraToolMaterials.REDSTONE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item redstone_pick = new ExtraPickaxeItem(ExtraToolMaterials.REDSTONE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item redstone_axe = new ExtraAxeItem(ExtraToolMaterials.REDSTONE, 5.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item redstone_hoe = new ExtraHoeItem(ExtraToolMaterials.REDSTONE, -2, -1.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item lapis_sword = new SwordItem(ExtraToolMaterials.LAPIS, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item lapis_shovel = new ShovelItem(ExtraToolMaterials.LAPIS, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item lapis_pick = new ExtraPickaxeItem(ExtraToolMaterials.LAPIS, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item lapis_axe = new ExtraAxeItem(ExtraToolMaterials.LAPIS, 5.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item lapis_hoe = new ExtraHoeItem(ExtraToolMaterials.LAPIS, -2, -1.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item emerald_sword = new SwordItem(ExtraToolMaterials.EMERALD, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item emerald_shovel = new ShovelItem(ExtraToolMaterials.EMERALD, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item emerald_pick = new ExtraPickaxeItem(ExtraToolMaterials.EMERALD, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item emerald_axe = new ExtraAxeItem(ExtraToolMaterials.EMERALD, 5.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item emerald_hoe = new ExtraHoeItem(ExtraToolMaterials.EMERALD, -2, -1.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item flint_sword = new SwordItem(ExtraToolMaterials.FLINT, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item flint_shovel = new ShovelItem(ExtraToolMaterials.FLINT, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item flint_pick = new ExtraPickaxeItem(ExtraToolMaterials.FLINT, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item flint_axe = new ExtraAxeItem(ExtraToolMaterials.FLINT, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item flint_hoe = new ExtraHoeItem(ExtraToolMaterials.FLINT, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item blackstone_sword = new SwordItem(ExtraToolMaterials.BLACKSTONE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item blackstone_shovel = new ShovelItem(ExtraToolMaterials.BLACKSTONE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item blackstone_pick = new ExtraPickaxeItem(ExtraToolMaterials.BLACKSTONE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item blackstone_axe = new ExtraAxeItem(ExtraToolMaterials.BLACKSTONE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item blackstone_hoe = new ExtraHoeItem(ExtraToolMaterials.BLACKSTONE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item basalt_sword = new SwordItem(ExtraToolMaterials.BASALT, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item basalt_shovel = new ShovelItem(ExtraToolMaterials.BASALT, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item basalt_pick = new ExtraPickaxeItem(ExtraToolMaterials.BASALT, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item basalt_axe = new ExtraAxeItem(ExtraToolMaterials.BASALT, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item basalt_hoe = new ExtraHoeItem(ExtraToolMaterials.BASALT, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item endstone_sword = new SwordItem(ExtraToolMaterials.ENDSTONE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item endstone_shovel = new ShovelItem(ExtraToolMaterials.ENDSTONE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item endstone_pick = new ExtraPickaxeItem(ExtraToolMaterials.ENDSTONE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item endstone_axe = new ExtraAxeItem(ExtraToolMaterials.ENDSTONE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item endstone_hoe = new ExtraHoeItem(ExtraToolMaterials.ENDSTONE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item crimson_sword = new SwordItem(ExtraToolMaterials.CRIMSON, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item crimson_shovel = new ShovelItem(ExtraToolMaterials.CRIMSON, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item crimson_pick = new ExtraPickaxeItem(ExtraToolMaterials.CRIMSON, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item crimson_axe = new ExtraAxeItem(ExtraToolMaterials.CRIMSON, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item crimson_hoe = new ExtraHoeItem(ExtraToolMaterials.CRIMSON, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item warped_sword = new SwordItem(ExtraToolMaterials.WARPED, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item warped_shovel = new ShovelItem(ExtraToolMaterials.WARPED, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item warped_pick = new ExtraPickaxeItem(ExtraToolMaterials.WARPED, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item warped_axe = new ExtraAxeItem(ExtraToolMaterials.WARPED, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item warped_hoe = new ExtraHoeItem(ExtraToolMaterials.WARPED, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item amethyst_sword = new SwordItem(ExtraToolMaterials.AMETHYST, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item amethyst_shovel = new ShovelItem(ExtraToolMaterials.AMETHYST, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item amethyst_pick = new ExtraPickaxeItem(ExtraToolMaterials.AMETHYST, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item amethyst_axe = new ExtraAxeItem(ExtraToolMaterials.AMETHYST, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item amethyst_hoe = new ExtraHoeItem(ExtraToolMaterials.AMETHYST, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item copper_sword = new SwordItem(ExtraToolMaterials.COPPER, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item copper_shovel = new ShovelItem(ExtraToolMaterials.COPPER, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item copper_pick = new ExtraPickaxeItem(ExtraToolMaterials.COPPER, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item copper_axe = new ExtraAxeItem(ExtraToolMaterials.COPPER, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item copper_hoe = new ExtraHoeItem(ExtraToolMaterials.COPPER, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item deepslate_sword = new SwordItem(ExtraToolMaterials.DEEPSLATE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item deepslate_shovel = new ShovelItem(ExtraToolMaterials.DEEPSLATE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item deepslate_pick = new ExtraPickaxeItem(ExtraToolMaterials.DEEPSLATE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item deepslate_axe = new ExtraAxeItem(ExtraToolMaterials.DEEPSLATE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item deepslate_hoe = new ExtraHoeItem(ExtraToolMaterials.DEEPSLATE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    
    public static final Item spruce_sword = new SwordItem(ExtraToolMaterials.SPRUCE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item spruce_shovel = new ShovelItem(ExtraToolMaterials.SPRUCE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item spruce_pick = new ExtraPickaxeItem(ExtraToolMaterials.SPRUCE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item spruce_axe = new ExtraAxeItem(ExtraToolMaterials.SPRUCE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item spruce_hoe = new ExtraHoeItem(ExtraToolMaterials.SPRUCE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));
    
    public static final Item birch_sword = new SwordItem(ExtraToolMaterials.BIRCH, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item birch_shovel = new ShovelItem(ExtraToolMaterials.BIRCH, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item birch_pick = new ExtraPickaxeItem(ExtraToolMaterials.BIRCH, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item birch_axe = new ExtraAxeItem(ExtraToolMaterials.BIRCH, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item birch_hoe = new ExtraHoeItem(ExtraToolMaterials.BIRCH, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));

    public static final Item jungle_sword = new SwordItem(ExtraToolMaterials.JUNGLE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item jungle_shovel = new ShovelItem(ExtraToolMaterials.JUNGLE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item jungle_pick = new ExtraPickaxeItem(ExtraToolMaterials.JUNGLE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item jungle_axe = new ExtraAxeItem(ExtraToolMaterials.JUNGLE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item jungle_hoe = new ExtraHoeItem(ExtraToolMaterials.JUNGLE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));

    public static final Item acacia_sword = new SwordItem(ExtraToolMaterials.ACACIA, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item acacia_shovel = new ShovelItem(ExtraToolMaterials.ACACIA, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item acacia_pick = new ExtraPickaxeItem(ExtraToolMaterials.ACACIA, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item acacia_axe = new ExtraAxeItem(ExtraToolMaterials.ACACIA, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item acacia_hoe = new ExtraHoeItem(ExtraToolMaterials.ACACIA, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));

    public static final Item dark_oak_sword = new SwordItem(ExtraToolMaterials.DARK_OAK, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item dark_oak_shovel = new ShovelItem(ExtraToolMaterials.DARK_OAK, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item dark_oak_pick = new ExtraPickaxeItem(ExtraToolMaterials.DARK_OAK, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
    public static final Item dark_oak_axe = new ExtraAxeItem(ExtraToolMaterials.DARK_OAK, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
    public static final Item dark_oak_hoe = new ExtraHoeItem(ExtraToolMaterials.DARK_OAK, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));

//    public static final Item mangrove_sword = new SwordItem(ExtraToolMaterials.MANGROVE, 3, -2.4F, (new FabricItemSettings()).group(sentimentality3));
//    public static final Item mangrove_shovel = new ShovelItem(ExtraToolMaterials.MANGROVE, 1.5F, -3.0F, (new FabricItemSettings()).group(sentimentality3));
//    public static final Item mangrove_pick = new ExtraPickaxeItem(ExtraToolMaterials.MANGROVE, 1, -2.8F, (new FabricItemSettings().group(sentimentality3)));
//    public static final Item mangrove_axe = new ExtraAxeItem(ExtraToolMaterials.MANGROVE, 7.0F, -3.2F, (new FabricItemSettings()).group(sentimentality3));
//    public static final Item mangrove_hoe = new ExtraHoeItem(ExtraToolMaterials.MANGROVE, -1, -2.0F, (new FabricItemSettings()).group(sentimentality3));

    public static JsonObject ARROW = null;
    public static JsonObject BREAD = null;
    public static JsonObject BLACKSTONE = null;
    public static JsonObject AMETHYST = null;
    public static JsonObject BLAZEROD = null;
    public static JsonObject BROWN_MUSHROOM = null;
    public static JsonObject RED_MUSHROOM = null;
    public static JsonObject CHARCOAL_BLOCK = null;
    public static JsonObject CHARCOAL_BLOCK_U = null;
    public static JsonObject CHARCOAL_NUGGET = null;
    public static JsonObject CHARCOAL_NUGGET_U = null;
    public static JsonObject CHESTS = null;
    public static JsonObject QUARTZ_PILLAR_CHISELED = null;
    public static JsonObject QUARTZ_CHISELED = null;
    public static JsonObject QUARTZ = null;
    public static JsonObject CHUNKLOADER = null;
    public static JsonObject CLAY = null;
    public static JsonObject COAL_NUGGET = null;
    public static JsonObject COAL_NUGGET_U = null;
    public static JsonObject DIORITE = null;
    public static JsonObject FEATHER = null;
    public static JsonObject FEATHER_U = null;
    public static JsonObject FLEATHER = null;
    public static JsonObject FLINT = null;
    public static JsonObject FURNACE = null;
    public static JsonObject GLOWSTONE = null;
    public static JsonObject GRANITE = null;
    public static JsonObject ANDESITE = null;
    public static JsonObject STICK_BUNDLE_L = null;
    public static JsonObject STICK_BUNDLE_L_U = null;
    public static JsonObject STICK_BUNDLE_S = null;
    public static JsonObject STICK_BUNDLE_S_U = null;
    public static JsonObject TORCH = null;
    public static JsonObject MOSSY_COBBLESTONE = null;
    public static JsonObject NAMETAG = null;
    public static JsonObject NOTCH_APPLE = null;
    public static JsonObject PAPER = null;
    public static JsonObject PDD = null;
    public static JsonObject SHULKERBOX = null;
    public static JsonObject SLIMEBALL = null;
    public static JsonObject SCL = null;
    public static JsonObject STRING = null;
    public static JsonObject TRIDENT = null;
    public static JsonObject WART = null;
    public static JsonObject GILDED_BLACKSTONE = null;

    public static JsonObject FLEATHERCOOK = null;
    public static JsonObject COPPER_BLOCK_FURNACE = null;
    public static JsonObject COPPER_BLOCK_BLAST = null;
    public static JsonObject IRON_BLOCK_FURNACE = null;
    public static JsonObject IRON_BLOCK_BLAST = null;
    public static JsonObject GOLD_BLOCK_FURNACE = null;
    public static JsonObject GOLD_BLOCK_BLAST = null;
    public static JsonObject RECLAIM_COPPER = null;
    public static JsonObject RECLAIM_IRON = null;
    public static JsonObject RECLAIM_GOLD = null;
    public static JsonObject RECLAIM_DIAMOND = null;

    public static JsonObject SADDLE = null;
    public static JsonObject HORSE_DIAMOND = null;
    public static JsonObject HORSE_GOLD = null;
    public static JsonObject HORSE_IRON = null;

    public static JsonObject CHAINBOOT = null;
    public static JsonObject CHAINPANT = null;
    public static JsonObject CHAINCHEST = null;
    public static JsonObject CHAINHELM = null;
    public static JsonObject COPPERBOOT = null;
    public static JsonObject COPPERPANT = null;
    public static JsonObject COPPERCHEST = null;
    public static JsonObject COPPERHELM = null;
    public static JsonObject WOOLBOOT = null;
    public static JsonObject WOOLPANT = null;
    public static JsonObject WOOLCHEST = null;
    public static JsonObject WOOLHELM = null;

    public static JsonObject ANDESITE_FURNACE = null;
    public static JsonObject ANDESITE_BLAST = null;
    public static JsonObject ANDESITE_SMOKER = null;
    public static JsonObject BLACKSTONE_FURNACE = null;
    public static JsonObject BLACKSTONE_BLAST = null;
    public static JsonObject BLACKSTONE_SMOKER = null;
    public static JsonObject BASALT_FURNACE = null;
    public static JsonObject BASALT_BLAST = null;
    public static JsonObject BASALT_SMOKER = null;
    public static JsonObject DEEPSLATE_FURNACE = null;
    public static JsonObject DEEPSLATE_BLAST = null;
    public static JsonObject DEEPSLATE_SMOKER = null;
    public static JsonObject DIORITE_FURNACE = null;
    public static JsonObject DIORITE_BLAST = null;
    public static JsonObject DIORITE_SMOKER = null;
    public static JsonObject ENDSTONE_FURNACE = null;
    public static JsonObject ENDSTONE_BLAST = null;
    public static JsonObject ENDSTONE_SMOKER = null;
    public static JsonObject GRANITE_FURNACE = null;
    public static JsonObject GRANITE_BLAST = null;
    public static JsonObject GRANITE_SMOKER = null;
    public static JsonObject NETHERRACK_FURNACE = null;
    public static JsonObject NETHERRACK_BLAST = null;
    public static JsonObject NETHERRACK_SMOKER = null;
    public static JsonObject SANDSTONE_FURNACE = null;
    public static JsonObject SANDSTONE_BLAST = null;
    public static JsonObject SANDSTONE_SMOKER = null;
    public static JsonObject RED_SANDSTONE_FURNACE = null;
    public static JsonObject RED_SANDSTONE_BLAST = null;
    public static JsonObject RED_SANDSTONE_SMOKER = null;
    
    public static JsonObject ANDESITE_1X = null;
    public static JsonObject ANDESITE_1XU = null;
    public static JsonObject ANDESITE_2X = null;
    public static JsonObject ANDESITE_2XU = null;
    public static JsonObject ANDESITE_3X = null;
    public static JsonObject ANDESITE_3XU = null;
    public static JsonObject ANDESITE_4X = null;
    public static JsonObject ANDESITE_4XU = null;
    public static JsonObject ANDESITE_5X = null;
    public static JsonObject ANDESITE_5XU = null;
    public static JsonObject ANDESITE_6X = null;
    public static JsonObject ANDESITE_6XU = null;
    public static JsonObject ANDESITE_7X = null;
    public static JsonObject ANDESITE_7XU = null;
    public static JsonObject ANDESITE_8X = null;
    public static JsonObject ANDESITE_8XU = null;
    public static JsonObject ANDESITE_9X = null;
    public static JsonObject ANDESITE_9XU = null;    
    
    public static JsonObject COBBLED_DEEPSLATE_1X = null;
    public static JsonObject COBBLED_DEEPSLATE_1XU = null;
    public static JsonObject COBBLED_DEEPSLATE_2X = null;
    public static JsonObject COBBLED_DEEPSLATE_2XU = null;
    public static JsonObject COBBLED_DEEPSLATE_3X = null;
    public static JsonObject COBBLED_DEEPSLATE_3XU = null;
    public static JsonObject COBBLED_DEEPSLATE_4X = null;
    public static JsonObject COBBLED_DEEPSLATE_4XU = null;
    public static JsonObject COBBLED_DEEPSLATE_5X = null;
    public static JsonObject COBBLED_DEEPSLATE_5XU = null;
    public static JsonObject COBBLED_DEEPSLATE_6X = null;
    public static JsonObject COBBLED_DEEPSLATE_6XU = null;
    public static JsonObject COBBLED_DEEPSLATE_7X = null;
    public static JsonObject COBBLED_DEEPSLATE_7XU = null;
    public static JsonObject COBBLED_DEEPSLATE_8X = null;
    public static JsonObject COBBLED_DEEPSLATE_8XU = null;
    public static JsonObject COBBLED_DEEPSLATE_9X = null;
    public static JsonObject COBBLED_DEEPSLATE_9XU = null;
    
    public static JsonObject COBBLESTONE_1X = null;
    public static JsonObject COBBLESTONE_1XU = null;
    public static JsonObject COBBLESTONE_2X = null;
    public static JsonObject COBBLESTONE_2XU = null;
    public static JsonObject COBBLESTONE_3X = null;
    public static JsonObject COBBLESTONE_3XU = null;
    public static JsonObject COBBLESTONE_4X = null;
    public static JsonObject COBBLESTONE_4XU = null;
    public static JsonObject COBBLESTONE_5X = null;
    public static JsonObject COBBLESTONE_5XU = null;
    public static JsonObject COBBLESTONE_6X = null;
    public static JsonObject COBBLESTONE_6XU = null;
    public static JsonObject COBBLESTONE_7X = null;
    public static JsonObject COBBLESTONE_7XU = null;
    public static JsonObject COBBLESTONE_8X = null;
    public static JsonObject COBBLESTONE_8XU = null;
    public static JsonObject COBBLESTONE_9X = null;
    public static JsonObject COBBLESTONE_9XU = null;

    public static JsonObject DIORITE_1X = null;
    public static JsonObject DIORITE_1XU = null;
    public static JsonObject DIORITE_2X = null;
    public static JsonObject DIORITE_2XU = null;
    public static JsonObject DIORITE_3X = null;
    public static JsonObject DIORITE_3XU = null;
    public static JsonObject DIORITE_4X = null;
    public static JsonObject DIORITE_4XU = null;
    public static JsonObject DIORITE_5X = null;
    public static JsonObject DIORITE_5XU = null;
    public static JsonObject DIORITE_6X = null;
    public static JsonObject DIORITE_6XU = null;
    public static JsonObject DIORITE_7X = null;
    public static JsonObject DIORITE_7XU = null;
    public static JsonObject DIORITE_8X = null;
    public static JsonObject DIORITE_8XU = null;
    public static JsonObject DIORITE_9X = null;
    public static JsonObject DIORITE_9XU = null;

    public static JsonObject DIRT_1X = null;
    public static JsonObject DIRT_1XU = null;
    public static JsonObject DIRT_2X = null;
    public static JsonObject DIRT_2XU = null;
    public static JsonObject DIRT_3X = null;
    public static JsonObject DIRT_3XU = null;
    public static JsonObject DIRT_4X = null;
    public static JsonObject DIRT_4XU = null;
    public static JsonObject DIRT_5X = null;
    public static JsonObject DIRT_5XU = null;
    public static JsonObject DIRT_6X = null;
    public static JsonObject DIRT_6XU = null;
    public static JsonObject DIRT_7X = null;
    public static JsonObject DIRT_7XU = null;
    public static JsonObject DIRT_8X = null;
    public static JsonObject DIRT_8XU = null;
    public static JsonObject DIRT_9X = null;
    public static JsonObject DIRT_9XU = null;

    public static JsonObject GRANITE_1X = null;
    public static JsonObject GRANITE_1XU = null;
    public static JsonObject GRANITE_2X = null;
    public static JsonObject GRANITE_2XU = null;
    public static JsonObject GRANITE_3X = null;
    public static JsonObject GRANITE_3XU = null;
    public static JsonObject GRANITE_4X = null;
    public static JsonObject GRANITE_4XU = null;
    public static JsonObject GRANITE_5X = null;
    public static JsonObject GRANITE_5XU = null;
    public static JsonObject GRANITE_6X = null;
    public static JsonObject GRANITE_6XU = null;
    public static JsonObject GRANITE_7X = null;
    public static JsonObject GRANITE_7XU = null;
    public static JsonObject GRANITE_8X = null;
    public static JsonObject GRANITE_8XU = null;
    public static JsonObject GRANITE_9X = null;
    public static JsonObject GRANITE_9XU = null;

    public static JsonObject GRAVEL_1X = null;
    public static JsonObject GRAVEL_1XU = null;
    public static JsonObject GRAVEL_2X = null;
    public static JsonObject GRAVEL_2XU = null;
    public static JsonObject GRAVEL_3X = null;
    public static JsonObject GRAVEL_3XU = null;
    public static JsonObject GRAVEL_4X = null;
    public static JsonObject GRAVEL_4XU = null;
    public static JsonObject GRAVEL_5X = null;
    public static JsonObject GRAVEL_5XU = null;
    public static JsonObject GRAVEL_6X = null;
    public static JsonObject GRAVEL_6XU = null;
    public static JsonObject GRAVEL_7X = null;
    public static JsonObject GRAVEL_7XU = null;
    public static JsonObject GRAVEL_8X = null;
    public static JsonObject GRAVEL_8XU = null;
    public static JsonObject GRAVEL_9X = null;
    public static JsonObject GRAVEL_9XU = null;

    public static JsonObject NETHERRACK_1X = null;
    public static JsonObject NETHERRACK_1XU = null;
    public static JsonObject NETHERRACK_2X = null;
    public static JsonObject NETHERRACK_2XU = null;
    public static JsonObject NETHERRACK_3X = null;
    public static JsonObject NETHERRACK_3XU = null;
    public static JsonObject NETHERRACK_4X = null;
    public static JsonObject NETHERRACK_4XU = null;
    public static JsonObject NETHERRACK_5X = null;
    public static JsonObject NETHERRACK_5XU = null;
    public static JsonObject NETHERRACK_6X = null;
    public static JsonObject NETHERRACK_6XU = null;
    public static JsonObject NETHERRACK_7X = null;
    public static JsonObject NETHERRACK_7XU = null;
    public static JsonObject NETHERRACK_8X = null;
    public static JsonObject NETHERRACK_8XU = null;
    public static JsonObject NETHERRACK_9X = null;
    public static JsonObject NETHERRACK_9XU = null;

    public static JsonObject SAND_1X = null;
    public static JsonObject SAND_1XU = null;
    public static JsonObject SAND_2X = null;
    public static JsonObject SAND_2XU = null;
    public static JsonObject SAND_3X = null;
    public static JsonObject SAND_3XU = null;
    public static JsonObject SAND_4X = null;
    public static JsonObject SAND_4XU = null;
    public static JsonObject SAND_5X = null;
    public static JsonObject SAND_5XU = null;
    public static JsonObject SAND_6X = null;
    public static JsonObject SAND_6XU = null;
    public static JsonObject SAND_7X = null;
    public static JsonObject SAND_7XU = null;
    public static JsonObject SAND_8X = null;
    public static JsonObject SAND_8XU = null;
    public static JsonObject SAND_9X = null;
    public static JsonObject SAND_9XU = null;
    public static JsonObject TUFF_1X = null;
    public static JsonObject TUFF_1XU = null;
    public static JsonObject TUFF_2X = null;
    public static JsonObject TUFF_2XU = null;
    public static JsonObject TUFF_3X = null;
    public static JsonObject TUFF_3XU = null;
    public static JsonObject TUFF_4X = null;
    public static JsonObject TUFF_4XU = null;
    public static JsonObject TUFF_5X = null;
    public static JsonObject TUFF_5XU = null;
    public static JsonObject TUFF_6X = null;
    public static JsonObject TUFF_6XU = null;
    public static JsonObject TUFF_7X = null;
    public static JsonObject TUFF_7XU = null;
    public static JsonObject TUFF_8X = null;
    public static JsonObject TUFF_8XU = null;
    public static JsonObject TUFF_9X = null;
    public static JsonObject TUFF_9XU = null;
    public static JsonObject CALCITE_1X = null;
    public static JsonObject CALCITE_1XU = null;
    public static JsonObject CALCITE_2X = null;
    public static JsonObject CALCITE_2XU = null;
    public static JsonObject CALCITE_3X = null;
    public static JsonObject CALCITE_3XU = null;
    public static JsonObject CALCITE_4X = null;
    public static JsonObject CALCITE_4XU = null;
    public static JsonObject CALCITE_5X = null;
    public static JsonObject CALCITE_5XU = null;
    public static JsonObject CALCITE_6X = null;
    public static JsonObject CALCITE_6XU = null;
    public static JsonObject CALCITE_7X = null;
    public static JsonObject CALCITE_7XU = null;
    public static JsonObject CALCITE_8X = null;
    public static JsonObject CALCITE_8XU = null;
    public static JsonObject CALCITE_9X = null;
    public static JsonObject CALCITE_9XU = null;
    public static JsonObject AMETHYST_AXE = null;
    public static JsonObject AMETHYST_HOE = null;
    public static JsonObject AMETHYST_PICKAXE = null;
    public static JsonObject AMETHYST_SHOVEL = null;
    public static JsonObject AMETHYST_SWORD = null;
    
    public static JsonObject ANDESITE_AXE = null;
    public static JsonObject ANDESITE_HOE = null;
    public static JsonObject ANDESITE_PICKAXE = null;
    public static JsonObject ANDESITE_SHOVEL = null;
    public static JsonObject ANDESITE_SWORD = null;
    
    public static JsonObject BASALT_AXE = null;
    public static JsonObject BASALT_HOE = null;
    public static JsonObject BASALT_PICKAXE = null;
    public static JsonObject BASALT_SHOVEL = null;
    public static JsonObject BASALT_SWORD = null;

    public static JsonObject BLACKSTONE_AXE = null;
    public static JsonObject BLACKSTONE_HOE = null;
    public static JsonObject BLACKSTONE_PICKAXE = null;
    public static JsonObject BLACKSTONE_SHOVEL = null;
    public static JsonObject BLACKSTONE_SWORD = null;

    public static JsonObject COPPER_AXE = null;
    public static JsonObject COPPER_HOE = null;
    public static JsonObject COPPER_PICKAXE = null;
    public static JsonObject COPPER_SHOVEL = null;
    public static JsonObject COPPER_SWORD = null;

    public static JsonObject CRIMSON_AXE = null;
    public static JsonObject CRIMSON_HOE = null;
    public static JsonObject CRIMSON_PICKAXE = null;
    public static JsonObject CRIMSON_SHOVEL = null;
    public static JsonObject CRIMSON_SWORD = null;

    public static JsonObject DEEPSLATE_AXE = null;
    public static JsonObject DEEPSLATE_HOE = null;
    public static JsonObject DEEPSLATE_PICKAXE = null;
    public static JsonObject DEEPSLATE_SHOVEL = null;
    public static JsonObject DEEPSLATE_SWORD = null;

    public static JsonObject DIORITE_AXE = null;
    public static JsonObject DIORITE_HOE = null;
    public static JsonObject DIORITE_PICKAXE = null;
    public static JsonObject DIORITE_SHOVEL = null;
    public static JsonObject DIORITE_SWORD = null;

    public static JsonObject EMERALD_AXE = null;
    public static JsonObject EMERALD_HOE = null;
    public static JsonObject EMERALD_PICKAXE = null;
    public static JsonObject EMERALD_SHOVEL = null;
    public static JsonObject EMERALD_SWORD = null;

    public static JsonObject ENDSTONE_AXE = null;
    public static JsonObject ENDSTONE_HOE = null;
    public static JsonObject ENDSTONE_PICKAXE = null;
    public static JsonObject ENDSTONE_SHOVEL = null;
    public static JsonObject ENDSTONE_SWORD = null;

    public static JsonObject FLINT_AXE = null;
    public static JsonObject FLINT_HOE = null;
    public static JsonObject FLINT_PICKAXE = null;
    public static JsonObject FLINT_SHOVEL = null;
    public static JsonObject FLINT_SWORD = null;

    public static JsonObject GRANITE_AXE = null;
    public static JsonObject GRANITE_HOE = null;
    public static JsonObject GRANITE_PICKAXE = null;
    public static JsonObject GRANITE_SHOVEL = null;
    public static JsonObject GRANITE_SWORD = null;

    public static JsonObject LAPIS_AXE = null;
    public static JsonObject LAPIS_HOE = null;
    public static JsonObject LAPIS_PICKAXE = null;
    public static JsonObject LAPIS_SHOVEL = null;
    public static JsonObject LAPIS_SWORD = null;

    public static JsonObject NETHERBRICK_AXE = null;
    public static JsonObject NETHERBRICK_HOE = null;
    public static JsonObject NETHERBRICK_PICKAXE = null;
    public static JsonObject NETHERBRICK_SHOVEL = null;
    public static JsonObject NETHERBRICK_SWORD = null;

    public static JsonObject RED_NETHERBRICK_AXE = null;
    public static JsonObject RED_NETHERBRICK_HOE = null;
    public static JsonObject RED_NETHERBRICK_PICKAXE = null;
    public static JsonObject RED_NETHERBRICK_SHOVEL = null;
    public static JsonObject RED_NETHERBRICK_SWORD = null;

    public static JsonObject NETHERRACK_AXE = null;
    public static JsonObject NETHERRACK_HOE = null;
    public static JsonObject NETHERRACK_PICKAXE = null;
    public static JsonObject NETHERRACK_SHOVEL = null;
    public static JsonObject NETHERRACK_SWORD = null;

    public static JsonObject QUARTZ_AXE = null;
    public static JsonObject QUARTZ_HOE = null;
    public static JsonObject QUARTZ_PICKAXE = null;
    public static JsonObject QUARTZ_SHOVEL = null;
    public static JsonObject QUARTZ_SWORD = null;

    public static JsonObject SANDSTONE_AXE = null;
    public static JsonObject SANDSTONE_HOE = null;
    public static JsonObject SANDSTONE_PICKAXE = null;
    public static JsonObject SANDSTONE_SHOVEL = null;
    public static JsonObject SANDSTONE_SWORD = null;

    public static JsonObject RED_SANDSTONE_AXE = null;
    public static JsonObject RED_SANDSTONE_HOE = null;
    public static JsonObject RED_SANDSTONE_PICKAXE = null;
    public static JsonObject RED_SANDSTONE_SHOVEL = null;
    public static JsonObject RED_SANDSTONE_SWORD = null;

    public static JsonObject REDSTONE_AXE = null;
    public static JsonObject REDSTONE_HOE = null;
    public static JsonObject REDSTONE_PICKAXE = null;
    public static JsonObject REDSTONE_SHOVEL = null;
    public static JsonObject REDSTONE_SWORD = null;

    public static JsonObject WARPED_AXE = null;
    public static JsonObject WARPED_HOE = null;
    public static JsonObject WARPED_PICKAXE = null;
    public static JsonObject WARPED_SHOVEL = null;
    public static JsonObject WARPED_SWORD = null;

    public static JsonObject SPRUCE_AXE = null;
    public static JsonObject SPRUCE_HOE = null;
    public static JsonObject SPRUCE_PICKAXE = null;
    public static JsonObject SPRUCE_SHOVEL = null;
    public static JsonObject SPRUCE_SWORD = null;

    public static JsonObject BIRCH_AXE = null;
    public static JsonObject BIRCH_HOE = null;
    public static JsonObject BIRCH_PICKAXE = null;
    public static JsonObject BIRCH_SHOVEL = null;
    public static JsonObject BIRCH_SWORD = null;
    
    public static JsonObject JUNGLE_AXE = null;
    public static JsonObject JUNGLE_HOE = null;
    public static JsonObject JUNGLE_PICKAXE = null;
    public static JsonObject JUNGLE_SHOVEL = null;
    public static JsonObject JUNGLE_SWORD = null;

    public static JsonObject ACACIA_AXE = null;
    public static JsonObject ACACIA_HOE = null;
    public static JsonObject ACACIA_PICKAXE = null;
    public static JsonObject ACACIA_SHOVEL = null;
    public static JsonObject ACACIA_SWORD = null;

    public static JsonObject DARK_OAK_AXE = null;
    public static JsonObject DARK_OAK_HOE = null;
    public static JsonObject DARK_OAK_PICKAXE = null;
    public static JsonObject DARK_OAK_SHOVEL = null;
    public static JsonObject DARK_OAK_SWORD = null;

//    public static JsonObject MANGROVE_AXE = null;
//    public static JsonObject MANGROVE_HOE = null;
//    public static JsonObject MANGROVE_PICKAXE = null;
//    public static JsonObject MANGROVE_SHOVEL = null;
//    public static JsonObject MANGROVE_SWORD = null;


    public static JsonObject MASS_ARROW = null;
}